FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["gunicorn", "webpage.wsgi:application", "--timeout", "120", "--bind", "0.0.0.0:8000"]

